spring.application.name=expense-sharing-app

#spring.security.oauth2.client.registration.google.client-id=<YOUR_GOOGLE_CLIENT_ID>
#spring.security.oauth2.client.registration.google.client-secret=<YOUR_GOOGLE_CLIENT_SECRET>
spring.security.oauth2.client.registration.google.client-id=175422136341-h4cf1itf5ti2h5jnjatrjl7ohdqj3fp8.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.client-secret=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

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true